# Generated by Django 4.2.7 on 2024-03-02 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_pages'),
        ),
        migrations.AlterField(
            model_name='landingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_page'),
        ),
        migrations.AlterField(
            model_name='landingimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='landing_page', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
    ]
