# Generated by Django 4.2.7 on 2024-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_category_image_alter_landingimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
