# Generated by Django 3.2.5 on 2024-03-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
