# Generated by Django 3.2.5 on 2024-03-09 04:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='brochure')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochure', to='landing_page.product')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
