# Generated by Django 3.2.5 on 2024-03-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochure',
            name='product',
        ),
        migrations.DeleteModel(
            name='LandingImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brochure',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
