# Generated by Django 3.2.5 on 2024-03-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0011_brochure_category_landingimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
