# Generated by Django 3.2.5 on 2024-03-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0012_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochure',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='LandingImage',
        ),
        migrations.DeleteModel(
            name='Brochure',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
