# Generated by Django 3.2.5 on 2024-03-06 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
