# Generated by Django 3.2.5 on 2024-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240306_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='username',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
