# Generated by Django 3.2.5 on 2024-03-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin1',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
