# Generated by Django 3.2.5 on 2024-03-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_admin1_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin1',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
